# Generated by Django 4.2.6 on 2023-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_sowperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_update', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('verify_by', models.CharField(max_length=255)),
                ('ration', models.CharField(default='Starter', max_length=255)),
            ],
        ),
    ]
