# Generated by Django 4.2.6 on 2023-10-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0017_feedstockupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive_user',
            field=models.BooleanField(default=False),
        ),
    ]
