# Generated by Django 4.1.3 on 2023-10-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0018_user_archive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='barcode_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
